# Database setup. The driver can be either sqlite, mysql or postgres. For
# SQLite, only the databasename is required, while MySQL and PostgreSQL also
# require username, password and perhaps a hostname.
# If you're trying out Bolt, just keep it set to SQLite for now.
database:
  driver: mysql
  databasename: dev_rhblog
  username: development
  password: devver
  host: localhost
  charset: utf8

# Show the 'debug' nut in the lower right corner for logged-in user.
debug: false
developer_notices: false

# By default, the debugbar is only shown to logged-in users. Use the following
# option to show it to all users. You probably do not want to use this in a
# production environment.
debug_show_loggedoff: true

# Use strict variables. This will make Bolt complain if you use {{ foo }},
# when foo doesn't exist.
strict_variables: true

# Settings for caching in parts of Bolt.
# - config:        Caches the parsed .yml files from /app/config. It's updated
#                  immediately when one of the files changes on disk. There
#                  should be no good reason to turn this off.
# - templates:     Caches rendered templates.
# - request:       Caches entire rendered pages like '/page/about', but only on
#                  GET requests.
# - duration:      The duration (in minutes) for the 'templates' and 'request'
#                  options. default is 10 minutes. Note that the duration is set
#                  on storing the cache. By lowering this value you will not
#                  invalidate currently cached items.
# - authenticated: Cache 'templates' and 'request' for logged-on users. In most
#                  cases you should *NOT* enable this, because it will cause
#                  side-effects if the website shows different content to
#                  authenticated users.
caching:
    config: false
    templates: false
    request: false
    duration: 10
    authenticated: false

# System debug logging
# This will enable intensive logging of Silex functions and will be very hard on
# performance and log file size.    The log file will be created in your cache
# directory.
#
# Enable this for short time periods only when diagnosing system issues.
# The level can be either: DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY
debuglog:
    enabled: false
    filename: bolt-debug.log
    level: DEBUG
