# This file defines the contenttypes on the website. See the documentation for
# details: http://docs.bolt.cm/content#defining-contenttypes

blogs:
    name: Blogs
    singular_name: Blog
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        teaser:
            type: textarea
        body:
            type: html
            height: 500px
    record_template: blog-detail.twig
    listing_template: blog-list.twig
    listing_records: 100
    sort: datepublish DESC
    recordsperpage: 10

#pages:
#    name: Pages
#    singular_name: Page
#    fields:
#        title:
#            type: text
#            class: large
#        slug:
#            type: slug
#            uses: title
#        introduction:
#            type: textarea
#        body:
#            type: html
#            height: 500px
#    sort: title
#    recordsperpage: 100
#    record_template: page.twig

quotes:
    name: Quotes
    singular_name: Quote
    fields:
        name:
            type: text
            class: large
        slug:
            type: slug
            uses: quote
        quote:
            type: textarea
    listing_template: quotes.twig
    listing_records: 100

# possible field types:
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# templateselect - varchar(256) - select with template filenames


# number (deprecated) - input type decimal(18,9), useful for storing number that need to be sortable
